qticodec2: disable SortIncludes in .clang-format
The feature SortIncludes of clang-format introduced
a compiling error for Clang 13. Revert header order
change introduced by clang-format.

error: templates must have C++ linkage

Change-Id: I37c4daad5aecbb08310c2cc9025f2bfced2b5d4e
Signed-off-by: Miaomiao Chen <quic_miaochen@quicinc.com>